USE [DBNotasCMS]
GO

/****** Object:  Table [dbo].[TCargo]    Script Date: 17/09/2026 11:45:57 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TCargo](
	[CodCargo] [smallint] NOT NULL,
	[NombreC] [varchar](50) NOT NULL,
	[CodU] [smallint] NOT NULL,
 CONSTRAINT [PK_TCargo] PRIMARY KEY CLUSTERED 
(
	[CodCargo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TCargo]  WITH CHECK ADD  CONSTRAINT [FK_TCargoTUnidad] FOREIGN KEY([CodU])
REFERENCES [dbo].[TUnidad] ([CodU])
GO

ALTER TABLE [dbo].[TCargo] CHECK CONSTRAINT [FK_TCargoTUnidad]
GO

