USE [DB_TRAMITES_EXTERNOS]
GO

/****** Object:  Table [dbo].[TUnidad]    Script Date: 17/09/2026 11:45:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TUnidad](
	[CodU] [smallint] NOT NULL,
	[NombU] [varchar](50) NOT NULL,
	[Activo] [bit] NOT NULL,
 CONSTRAINT [PK_TUnidad] PRIMARY KEY CLUSTERED 
(
	[CodU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

